export default () => (
    <>
        <h2>Comments</h2>
        <script
            src="https://giscus.app/client.js"
            data-repo="apacheli/apacheli.github.io"
            data-repo-id="R_kgDOLt0Zpg"
            data-category="General"
            data-category-id="DIC_kwDOLt0Zps4CkjKo"
            data-mapping="title"
            data-strict="1"
            data-reactions-enabled="1"
            data-emit-metadata="1"
            data-input-position="top"
            data-theme="preferred_color_scheme"
            data-lang="en"
            data-loading="lazy"
            crossorigin="anonymous"
            async
        />
    </>
);
